openapi: 3.0.3
info:
  title: Math API
  description: Secure Math API with JWT authentication and operation history
  version: 1.0.0

servers:
  - url: http://localhost:8000

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:

    User:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string

    Numbers:
      type: object
      required:
        - n1
        - n2
      properties:
        n1:
          type: number
          format: float
        n2:
          type: number
          format: float

    SingleNumber:
      type: object
      required:
        - n1
      properties:
        n1:
          type: number
          format: float

    TokenResponse:
      type: object
      properties:
        access_token:
          type: string
        token_type:
          type: string
          example: bearer

    OperationOut:
      type: object
      properties:
        id:
          type: integer
        operation_type:
          type: string
        n1:
          type: number
          format: float
        n2:
          type: number
          format: float
          nullable: true
        result:
          type: number
          format: float
        timestamp:
          type: string
          format: date-time

paths:

  /register:
    post:
      summary: Register new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: User registered successfully
        '400':
          description: Username already exists

  /login:
    post:
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        '400':
          description: Invalid credentials

  /api/sum:
    post:
      summary: Sum two numbers
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Numbers'
      responses:
        '200':
          description: Sum result

  /api/sub:
    post:
      summary: Subtract two numbers
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Numbers'
      responses:
        '200':
          description: Subtraction result

  /api/mul:
    post:
      summary: Multiply two numbers
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Numbers'
      responses:
        '200':
          description: Multiplication result

  /api/div:
    post:
      summary: Divide two numbers
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Numbers'
      responses:
        '200':
          description: Division result
        '400':
          description: Cannot divide by zero

  /api/pow:
    post:
      summary: Power operation
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Numbers'
      responses:
        '200':
          description: Power result

  /api/sqrt:
    post:
      summary: Square root
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SingleNumber'
      responses:
        '200':
          description: Square root result
        '400':
          description: Cannot calculate square root of negative number

  /api/user/{user_id}/history/all:
    get:
      summary: Get all user operations
      security:
        - bearerAuth: []
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: List of operations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OperationOut'
        '403':
          description: Not allowed

  /api/user/{user_id}/history/{operation_id}:
    get:
      summary: Get single operation
      security:
        - bearerAuth: []
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
        - name: operation_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Operation details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationOut'
        '403':
          description: Not allowed
        '404':
          description: Operation not found
