openapi: 3.0.3
info:
  title: Math API
  description: API for sum, multiply, power, subtract, divide, and square root operations with robust error handling
  version: "1.1.0"
servers:
  - url: http://127.0.0.1:8000
paths:
  /api/sum:
    post:
      summary: Add two numbers
      description: Returns the sum of `n1` and `n2`
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                n1:
                  type: number
                  example: 10
                n2:
                  type: number
                  example: 20
      responses:
        '200':
          description: Sum result
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: number
                    example: 30

  /api/mul:
    post:
      summary: Multiply two numbers
      description: Returns the product of `n1` and `n2`
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                n1:
                  type: number
                  example: 5
                n2:
                  type: number
                  example: 6
      responses:
        '200':
          description: Multiplication result
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: number
                    example: 30

  /api/pow:
    post:
      summary: Power of a number
      description: Returns `n1` raised to the power of `n2`
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                n1:
                  type: number
                  example: 2
                n2:
                  type: number
                  example: 3
      responses:
        '200':
          description: Power result
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: number
                    example: 8

  /api/sub:
    post:
      summary: Subtract two numbers
      description: Returns `n1 - n2`
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                n1:
                  type: number
                  example: 10
                n2:
                  type: number
                  example: 4
      responses:
        '200':
          description: Subtraction result
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: number
                    example: 6

  /api/div:
    post:
      summary: Divide two numbers
      description: Returns `n1 / n2`. Throws error if `n2` is 0
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                n1:
                  type: number
                  example: 10
                n2:
                  type: number
                  example: 0
      responses:
        '200':
          description: Division result
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: number
                    example: 2
        '400':
          description: Error if dividing by zero
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Cannot divide by zero

  /api/sqrt:
    post:
      summary: Square root
      description: Returns the square root of `n1`. Throws error if `n1 < 0`
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                n1:
                  type: number
                  example: 25
      responses:
        '200':
          description: Square root result
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: number
                    example: 5
        '400':
          description: Error if `n1` is negative
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Cannot take square root of a negative number
