openapi: 3.0.3
info:
  title: Math API with Authentication
  version: 1.0.0
  description: A simple API for mathematical operations and user registration/login.
paths:
  /register:
    post:
      summary: Register a new user
      operationId: register
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Username already exists
  /login:
    post:
      summary: Login and get access token
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Access token
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  token_type:
                    type: string
        '400':
          description: Invalid credentials
  /api/sum:
    post:
      summary: Add two numbers
      operationId: sum_numbers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Numbers'
      responses:
        '200':
          description: Result of addition
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: number
                    format: float
  /api/mul:
    post:
      summary: Multiply two numbers
      operationId: mul_numbers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Numbers'
      responses:
        '200':
          description: Result of multiplication
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: number
                    format: float
  /api/pow:
    post:
      summary: Raise n1 to the power of n2
      operationId: pow_numbers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Numbers'
      responses:
        '200':
          description: Result of exponentiation
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: number
                    format: float
  /api/sub:
    post:
      summary: Subtract n2 from n1
      operationId: sub_numbers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Numbers'
      responses:
        '200':
          description: Result of subtraction
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: number
                    format: float
  /api/div:
    post:
      summary: Divide n1 by n2
      operationId: div_numbers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Numbers'
      responses:
        '200':
          description: Result of division
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: number
                    format: float
        '400':
          description: Cannot divide by zero
  /api/sqrt:
    post:
      summary: Calculate square root of n1
      operationId: sqrt_number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SingleNumber'
      responses:
        '200':
          description: Result of square root
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: number
                    format: float
        '400':
          description: Cannot calculate square root of negative number
components:
  schemas:
    User:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string
    Numbers:
      type: object
      required:
        - n1
        - n2
      properties:
        n1:
          type: number
          format: float
        n2:
          type: number
          format: float
    SingleNumber:
      type: object
      required:
        - n1
      properties:
        n1:
          type: number
          format: float
